/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type PlanHighlight = {
  _type: "planHighlight";
  text: string;
  availability: "available" | "planned";
  plannedNote?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
>;

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type WaitlistEntry = {
  _id: string;
  _type: "waitlistEntry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  company?: string;
  teamSize?: string;
  crm?: string;
  planInterest?: string;
  submittedAt?: string;
};

export type ChangelogEntry = {
  _id: string;
  _type: "changelogEntry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  kind: "new" | "improved" | "fixed";
  releasedAt: string;
  summary: string;
  body?: BlockContent;
};

export type CustomerStory = {
  _id: string;
  _type: "customerStory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  company: string;
  slug: Slug;
  industry?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  summary: string;
  quote?: {
    text?: string;
    person?: string;
    role?: string;
  };
  results?: Array<{
    metric: string;
    label: string;
    _type: "result";
    _key: string;
  }>;
  body?: BlockContent;
  publishedAt: string;
  seo?: Seo;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt?: string;
  coverImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: BlockContent;
  author?: AuthorReference;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt: string;
  seo?: Seo;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  role?: string;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  bio?: string;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question: string;
  answer: string;
  topic: "pricing" | "product" | "security";
};

export type ComparisonRow = {
  _id: string;
  _type: "comparisonRow";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  scenario: string;
  ours: string;
  competitorValues?: Array<{
    competitor: string;
    value: string;
    _type: "competitorValue";
    _key: string;
  }>;
  sortOrder: number;
};

export type UsageRate = {
  _id: string;
  _type: "usageRate";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  itemKey:
    | "outbound_min"
    | "inbound_min"
    | "sms_segment"
    | "local_number"
    | "extra_seat"
    | "ai_min";
  label: string;
  unitPriceCents: number;
  unit: string;
  displayRate: string;
  sortOrder: number;
};

export type PlanReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "plan";
};

export type Plan = {
  _id: string;
  _type: "plan";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  planKey: "solo" | "team" | "agency" | "enterprise";
  audience: string;
  monthlyPrice?: number;
  includedSeats?: number;
  seatsNote?: string;
  includedAiMinutes?: number;
  inheritsFrom?: PlanReference;
  highlights?: Array<
    {
      _key: string;
    } & PlanHighlight
  >;
  cta: "trial" | "sales";
  badge?: "popular";
  sortOrder: number;
};

export type FaqReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faq";
};

export type PricingPage = {
  _id: string;
  _type: "pricingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  annualDiscountPercent: number;
  trial?: {
    days: number;
    freeMinutes: number;
    cardRequired?: boolean;
  };
  competitors?: Array<{
    name: string;
    sourceUrl: string;
    _type: "competitor";
    _key: string;
  }>;
  comparisonCheckedOn?: string;
  comparisonFootnote?: string;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  tagline?: string;
  description?: string;
  announcement?: {
    text?: string;
    href?: string;
  };
  seo?: Seo;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | PlanHighlight
  | SanityImageAssetReference
  | BlockContent
  | Seo
  | WaitlistEntry
  | ChangelogEntry
  | CustomerStory
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Category
  | AuthorReference
  | CategoryReference
  | Post
  | Author
  | Faq
  | ComparisonRow
  | UsageRate
  | PlanReference
  | Plan
  | FaqReference
  | PricingPage
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../src/sanity/queries.ts
// Variable: PRICE_BOOK_QUERY
// Query: {  "page": *[_id == "pricingPage"][0]{    annualDiscountPercent,    trial{ days, freeMinutes, cardRequired },    competitors[]{ name, sourceUrl },    comparisonCheckedOn,    comparisonFootnote,    "faq": faqs[]->{ question, answer }  },  "plans": *[_type == "plan" && defined(planKey)] | order(sortOrder asc){    planKey, name, audience, monthlyPrice, includedSeats, seatsNote, includedAiMinutes,    "inheritsFrom": inheritsFrom->planKey,    highlights[]{ _key, text, availability, plannedNote },    cta, badge  },  "usageRates": *[_type == "usageRate" && defined(itemKey)] | order(sortOrder asc){    itemKey, label, unitPriceCents, unit, displayRate  },  "comparison": *[_type == "comparisonRow"] | order(sortOrder asc){    scenario, ours, competitorValues[]{ competitor, value }  }}
export type PRICE_BOOK_QUERY_RESULT = {
  page:
    | {
        annualDiscountPercent: null;
        trial: null;
        competitors: null;
        comparisonCheckedOn: null;
        comparisonFootnote: null;
        faq: null;
      }
    | {
        annualDiscountPercent: number;
        trial: {
          days: number;
          freeMinutes: number;
          cardRequired: boolean | null;
        } | null;
        competitors: Array<{
          name: string;
          sourceUrl: string;
        }> | null;
        comparisonCheckedOn: string | null;
        comparisonFootnote: string | null;
        faq: Array<{
          question: string;
          answer: string;
        }> | null;
      }
    | null;
  plans: Array<{
    planKey: "agency" | "enterprise" | "solo" | "team";
    name: string;
    audience: string;
    monthlyPrice: number | null;
    includedSeats: number | null;
    seatsNote: string | null;
    includedAiMinutes: number | null;
    inheritsFrom: "agency" | "enterprise" | "solo" | "team" | null;
    highlights: Array<{
      _key: string;
      text: string;
      availability: "available" | "planned";
      plannedNote: string | null;
    }> | null;
    cta: "sales" | "trial";
    badge: "popular" | null;
  }>;
  usageRates: Array<{
    itemKey:
      | "ai_min"
      | "extra_seat"
      | "inbound_min"
      | "local_number"
      | "outbound_min"
      | "sms_segment";
    label: string;
    unitPriceCents: number;
    unit: string;
    displayRate: string;
  }>;
  comparison: Array<{
    scenario: string;
    ours: string;
    competitorValues: Array<{
      competitor: string;
      value: string;
    }> | null;
  }>;
};

// Source: ../src/sanity/queries.ts
// Variable: POSTS_INDEX_QUERY
// Query: *[_type == "post" && defined(slug.current) && publishedAt <= now()] | order(publishedAt desc)[0...24]{  _id, title, "slug": slug.current, excerpt, publishedAt,  coverImage{ asset, alt, hotspot, crop },  "author": author->{ name, role },  "categories": categories[]->title}
export type POSTS_INDEX_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  publishedAt: string;
  coverImage: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  author: {
    name: string;
    role: string | null;
  } | null;
  categories: Array<string> | null;
}>;

// Source: ../src/sanity/queries.ts
// Variable: POST_DETAIL_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{  _id, title, "slug": slug.current, excerpt, publishedAt, body,  coverImage{ asset, alt, hotspot, crop },  "author": author->{ name, role, bio },  "categories": categories[]->title,  seo{ title, description }}
export type POST_DETAIL_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  excerpt: string | null;
  publishedAt: string;
  body: BlockContent | null;
  coverImage: {
    asset: SanityImageAssetReference | null;
    alt: string | null;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
  } | null;
  author: {
    name: string;
    role: string | null;
    bio: string | null;
  } | null;
  categories: Array<string> | null;
  seo: {
    title: string | null;
    description: string | null;
  } | null;
} | null;

// Source: ../src/sanity/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{ "slug": slug.current }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: ../src/sanity/queries.ts
// Variable: CHANGELOG_QUERY
// Query: *[_type == "changelogEntry"] | order(releasedAt desc)[0...50]{  _id, title, kind, releasedAt, summary}
export type CHANGELOG_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  kind: "fixed" | "improved" | "new";
  releasedAt: string;
  summary: string;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '{\n  "page": *[_id == "pricingPage"][0]{\n    annualDiscountPercent,\n    trial{ days, freeMinutes, cardRequired },\n    competitors[]{ name, sourceUrl },\n    comparisonCheckedOn,\n    comparisonFootnote,\n    "faq": faqs[]->{ question, answer }\n  },\n  "plans": *[_type == "plan" && defined(planKey)] | order(sortOrder asc){\n    planKey, name, audience, monthlyPrice, includedSeats, seatsNote, includedAiMinutes,\n    "inheritsFrom": inheritsFrom->planKey,\n    highlights[]{ _key, text, availability, plannedNote },\n    cta, badge\n  },\n  "usageRates": *[_type == "usageRate" && defined(itemKey)] | order(sortOrder asc){\n    itemKey, label, unitPriceCents, unit, displayRate\n  },\n  "comparison": *[_type == "comparisonRow"] | order(sortOrder asc){\n    scenario, ours, competitorValues[]{ competitor, value }\n  }\n}': PRICE_BOOK_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current) && publishedAt <= now()] | order(publishedAt desc)[0...24]{\n  _id, title, "slug": slug.current, excerpt, publishedAt,\n  coverImage{ asset, alt, hotspot, crop },\n  "author": author->{ name, role },\n  "categories": categories[]->title\n}': POSTS_INDEX_QUERY_RESULT;
    '*[_type == "post" && slug.current == $slug][0]{\n  _id, title, "slug": slug.current, excerpt, publishedAt, body,\n  coverImage{ asset, alt, hotspot, crop },\n  "author": author->{ name, role, bio },\n  "categories": categories[]->title,\n  seo{ title, description }\n}': POST_DETAIL_QUERY_RESULT;
    '*[_type == "post" && defined(slug.current)]{ "slug": slug.current }': POST_SLUGS_QUERY_RESULT;
    '*[_type == "changelogEntry"] | order(releasedAt desc)[0...50]{\n  _id, title, kind, releasedAt, summary\n}': CHANGELOG_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module "@sanity/client" {
  interface SanityQueries extends globalThis.SanityQueries {}
}
